
import * as color from './colors'


export const themeLight = {
    backgroundPage: color.graySmoothX4,
    backgroundLayout: color.white,

    iconHeader: color.blackSmooth,
    iconHoverHeader: color.white,
    iconHoverBackgroundHeader: color.red,
    iconThemeHoverBackgroundHeader: color.blue,

    titleSidebar: color.blackSmooth,
    textSidebar: color.greenSmooth,
    textHoverActiveSidebar: color.white,
    textHoverActiveSidebar2: color.white,
    textHoverSidebar: color.red,
    iconSidebar: color.greenSmooth,
    buttonSidebar: color.graySmoothX4,

    backgroundKPIDashboard: color.white,
    titleKPIDashboard: color.blackSmooth,
    textKPIDashboard: color.gray,
    titleReviewsDashboard: color.blackSmooth,
    iconDashboard: color.red,
    iconBackgroundDashboard: color.redSmoothX2,
    iconHoverDashboard: color.white,
    iconHoverBackgroundDashboard: color.red,
    swiperNavigationButton: color.white,
    swiperPaginationButton: color.white,
    swiperPaginationButtonSelected: color.white,

    backgroundBookingDetails: color.white,
    textBookingDetails: color.blackSmooth,
    idBookingDetails: color.greenSmooth,
    iconOptionsBookingDetails: color.blackSmooth,
    iconPhoneBookingDetails: color.blackSmooth,
    iconPhoneBackgroundBookingDetails: color.white,
    iconFacilityBackgroundBookingDetails: color.graySmoothX3,
    iconPhoneBorderBookingDetails: color.graySmoothX3,
    textButtonBookingDetails: color.white,
    backgroundButtonBookingDetails: color.greenDark,
    textInfoBookingDetails: color.blackSmooth,

    iconForm: color.blackSmooth,
    iconEye: color.white,
    iconEyeBackground: color.greenDark,
    borderElementForm: color.graySmoothX2,
    borderElementHoverForm: color.red,
    backgroundElementForm: color.white,
    optionHoverForm: color.redSmooth,
    textForm: color.blackSmooth,
    textLabelForm: color.blackSmooth,
    textLabelStatusForm: color.greenSmoothX2,
    buttonFormAdd: color.green,
    buttonFormDelete: color.red,
    buttonFormText: color.white,
    textPlaceholderForm: color.graySmoothX3,

    backgroundTable: color.white,
    nameTable: color.greenSmoothX2,
    textTable: color.blackSmooth,
    textTable2: color.white,
    borderTable: color.graySmoothX3,
    iconTable: color.blackSmooth,
    iconBackgroundTable: color.white,
    buttonOptionText: color.white,
    buttonOptionTextDisabled: color.white,
    buttonOptionBackground: color.graySmooth,
    buttonOptionBackgroundDisabled: color.graySmoothX2,
    iconOptionsTable: color.blackSmooth,
    containerOptionsTable: color.graySmoothX3,
    containerOptionsNotInTable: color.graySmoothX3,
    checkInTextTable: color.green,
    checkInBackgroundTable: color.greenSmoothX3,
    inProgressTextTable: color.orange,
    inProgressBackgroundTable: color.yellowSmooth,
    checkOutTextTable: color.red,
    checkOutBackgroundTable: color.redSmooth,
    buttonTextTable: color.blackSmooth,
    buttonBackgroundTable: color.graySmoothX4,
    availableTable: color.greenSmoothX2,
    notAvailableTable: color.red,

    textButtonPagination: color.white,
    backgroundButtonPagination: color.greenDark,
    textPageCountPagination: color.blackSmooth,

    textDisplaySelector: color.blackSmooth,
    hoverDisplaySelector: color.blueSmooth,
    hoverBorderDisplaySelector: color.blueSmooth,
    selectedDisplaySelector: color.blackSmooth,

    checkInBookingArticle: color.green,
    inProgressBookingArticle: color.yellowSmooth,
    checkOutBookingArticle: color.red,
    nameClientBookingArticle: color.blackSmooth,
    specialRequestBookingArticle: color.gray,
    buttonBookingArticle: color.blackSmooth,
    buttonBackgroundBookingArticle: color.graySmoothX4,
    backgroundBookingArticle: color.white,

    backgroundPopup: color.whiteSmooth,
    textPopup: color.blackSmooth,
    buttonPopup: color.white,
    buttonYesBackgroundPopup: color.greenSmoothX4,
    buttonNoBackgroundPopup: color.red,
    iconPopup: color.blackSmooth,

    textButtonCreate: color.white,
    textButtonCreateDisabled: color.white,
    backgroundButtonCreate: color.greenDark,
    backgroundButtonCreateDisabled: color.graySmooth,

    textSearchTerm: color.blackSmooth,

    boxShadowCustom: `0 0.25em 0.5em ${color.graySmoothX3}`,
    boxShadowCustomProfile: `0 0.25em 0.5em ${color.graySmoothX3}`,
    boxShadowCustomWithHover: `0 0.25em 0.5em ${color.gray}`
}



export const themeDark = {
    backgroundPage: color.grayDark,
    backgroundLayout: color.blackSmoothX2,

    iconHeader: color.whiteSmooth,
    iconHoverHeader: color.whiteSmooth,
    iconHoverBackgroundHeader: color.red,
    iconThemeHoverBackgroundHeader: color.blue,

    titleSidebar: color.whiteSmooth,
    textSidebar: color.whiteSmooth,
    textHoverActiveSidebar: color.blackSmoothX2,
    textHoverActiveSidebar2: color.whiteSmooth,
    textHoverSidebar: color.red,
    iconSidebar: color.whiteSmooth,
    buttonSidebar: color.graySmoothX4,

    backgroundKPIDashboard: color.graySmoothX2,
    titleKPIDashboard: color.blackSmooth,
    textKPIDashboard: color.grayDark,
    titleReviewsDashboard: color.whiteSmooth,
    iconDashboard: color.red,
    iconBackgroundDashboard: color.redSmoothX2,
    iconHoverDashboard: color.whiteSmooth,
    iconHoverBackgroundDashboard: color.red,
    swiperNavigationButton: color.whiteSmooth,
    swiperPaginationButton: color.whiteSmooth,
    swiperPaginationButtonSelected: color.whiteSmooth,

    backgroundBookingDetails: color.graySmoothX2,
    textBookingDetails: color.blackSmooth,
    idBookingDetails: color.greenSmooth,
    iconOptionsBookingDetails: color.blackSmooth,
    iconPhoneBookingDetails: color.blackSmooth,
    iconPhoneBackgroundBookingDetails: color.whiteSmooth,
    iconFacilityBackgroundBookingDetails: color.whiteSmooth,
    iconPhoneBorderBookingDetails: color.graySmoothX3,
    textButtonBookingDetails: color.whiteSmooth,
    backgroundButtonBookingDetails: color.greenSmoothX4,
    textInfoBookingDetails: color.blackSmooth,

    iconForm: color.whiteSmooth,
    iconEye: color.whiteSmooth,
    iconEyeBackground: color.greenSmoothX4,
    borderElementForm: color.blackSmooth,
    borderElementHoverForm: color.red,
    backgroundElementForm: color.whiteSmooth,
    optionHoverForm: color.redSmooth,
    textForm: color.blackSmooth,
    textLabelForm: color.whiteSmooth,
    textLabelStatusForm: color.greenSmoothX4,
    buttonFormAdd: color.green,
    buttonFormDelete: color.red,
    buttonFormText: color.white,
    textPlaceholderForm: color.graySmoothX3,

    backgroundTable: color.graySmoothX2,
    nameTable: color.greenSmoothX4,
    textTable: color.blackSmooth,
    textTable2: color.whiteSmooth,
    borderTable: color.graySmoothX4,
    iconTable: color.blackSmooth,
    iconBackgroundTable: color.graySmoothX2,
    buttonOptionText: color.blackSmooth,
    buttonOptionTextDisabled: color.blackSmooth,
    buttonOptionBackground: color.graySmoothX3,
    buttonOptionBackgroundDisabled: color.graySmooth,
    iconBackground: color.graySmoothX2,
    iconOptionsTable: color.blackSmooth,
    containerOptionsTable: color.gray,
    containerOptionsNotInTable: color.gray,
    checkInTextTable: color.green,
    checkInBackgroundTable: color.greenSmoothX3,
    inProgressTextTable: color.orange,
    inProgressBackgroundTable: color.yellowSmooth,
    checkOutTextTable: color.red,
    checkOutBackgroundTable: color.redSmooth,
    buttonTextTable: color.blackSmooth,
    buttonBackgroundTable: color.graySmoothX4,
    availableTable: color.greenSmoothX4,
    notAvailableTable: color.red,

    textButtonPagination: color.whiteSmooth,
    backgroundButtonPagination: color.greenSmoothX4,
    textPageCountPagination: color.whiteSmooth,

    textDisplaySelector: color.whiteSmooth,
    hoverDisplaySelector: color.whiteSmooth,
    hoverBorderDisplaySelector: color.whiteSmooth,
    selectedDisplaySelector: color.orange,

    checkInBookingArticle: color.green,
    inProgressBookingArticle: color.yellowSmooth,
    checkOutBookingArticle: color.red,
    nameClientBookingArticle: color.blackSmooth,
    specialRequestBookingArticle: color.grayDark,
    buttonBookingArticle: color.blackSmooth,
    buttonBackgroundBookingArticle: color.graySmoothX4,
    backgroundBookingArticle: color.graySmoothX2,

    backgroundPopup: color.graySmoothX4,
    textPopup: color.blackSmooth,
    buttonPopup: color.whiteSmooth,
    buttonYesBackgroundPopup: color.greenSmoothX4,
    buttonNoBackgroundPopup: color.red,
    iconPopup: color.blackSmooth,

    textButtonCreate: color.whiteSmooth,
    textButtonCreateDisabled: color.whiteSmooth,
    backgroundButtonCreate: color.greenSmoothX4,
    backgroundButtonCreateDisabled: color.graySmooth,

    textSearchTerm: color.blackSmooth,

    boxShadowCustom: `0 0.25em 0.5em ${color.blackSmoothX2}`,
    boxShadowCustomProfile: `0 0.25em 0.5em ${color.graySmooth}`,
    boxShadowCustomWithHover: `0 0.25em 0.5em ${color.graySmooth}`
}